package mahaul

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"os"
	"slices"
	"text/template"

	"github.com/emadalam/go-mahaul/internal/helpers"
)

const codeTemplate = `// Code generated by go-mahaul generator; DO NOT EDIT.
package {{.PackageName}}

import (
	{{range .Imports}}
	"{{.}}"
	{{end}}
)

var config = {{printf "%#v" .Config}}

func Validate() (errs map[string]error) {
	return mahaul.ValidateEnv(*config)
}

func WarnValidate() (errs map[string]error) {
	return mahaul.WarnValidateEnv(*config)
}

func MustValidate() {
	mahaul.MustValidateEnv(*config)
}

type envVals mahaul.EnvVals
var Value = envVals{}

{{range .EnvMethods}}
func(_ envVals) {{.FnName}}() (val {{.RetType}}) {
	return mahaul.GetenvAs[{{.RetType}}]((*config)["{{.CnfKey}}"], "{{.CnfKey}}")
}
{{end}}
`

type GeneratorCnf struct {
	PackageName string
	Config      *map[string]EnvVarConf
}

type GeneratorEnvMethodMetadata struct {
	CnfKey  string
	FnName  string
	RetType string
	// TODO: add and support custom descriptions
	// TODO: add additional imports metadata in Imports filed
}

type Generator struct {
	PackageName string
	Imports     []string
	Config      *map[string]EnvVarConf
	EnvMethods  []GeneratorEnvMethodMetadata
}

func (gmd *Generator) Make(c GeneratorCnf) error {
	if c.Config == nil {
		return errors.New("Config is required")
	}

	pkgName := c.PackageName
	if pkgName == "" {
		pkgName = "env"
	}

	envMethods := getEnvMethodsMetadata(*c.Config)

	imports := []string{"github.com/emadalam/go-mahaul/mahaul"}
	for _, m := range envMethods {
		// TODO: use imports metadata from Imports filed
		if m.RetType == "*url.URL" {
			imports = append(imports, "net/url")
		}
	}
	slices.Sort(imports)
	imports = slices.Compact(imports)

	gmd.PackageName = pkgName
	gmd.Config = c.Config
	gmd.Imports = imports
	gmd.EnvMethods = envMethods

	return nil
}

func (m Generator) Generate() ([]byte, error) {
	codeBytes, err := m.CodeBytes()
	if err != nil {
		return codeBytes, err
	}

	return codeBytes, nil
}

func getEnvMethodsMetadata(config map[string]EnvVarConf) []GeneratorEnvMethodMetadata {
	var methodsMetadata []GeneratorEnvMethodMetadata
	for key, c := range config {
		methodsMetadata = append(methodsMetadata, getEnvMethodMetadata(c, key))
	}

	return methodsMetadata
}

func getEnvMethodMetadata(c EnvVarConf, key string) GeneratorEnvMethodMetadata {
	fnName := helpers.UpperCamelCase(key)
	retType := c.Type.GoType()

	if retType == "" {
		fmt.Fprintf(os.Stdout, "warning: invalid type %#v for %s, defaulting to %#v type\n", c.Type, key, StringType)
		retType = EnvVarConf{Type: StringType}.Type.GoType()
	}

	return GeneratorEnvMethodMetadata{
		CnfKey:  key,
		FnName:  fnName,
		RetType: retType,
	}
}

func (cm Generator) CodeBytes() (codeBytes []byte, err error) {
	tpl := template.Must(template.New("code").Parse(codeTemplate))

	var buf bytes.Buffer
	if err := tpl.Execute(&buf, cm); err != nil {
		return nil, err
	}

	formattedCode, err := format.Source(buf.Bytes())

	if err != nil {
		fmt.Printf("Warning: failed to format generated code: %v\n", err)
		return buf.Bytes(), err
	}

	return formattedCode, nil
}

func (cm Generator) String() string {
	cBytes, err := cm.CodeBytes()
	if err != nil {
		return ""
	}

	return string(cBytes)
}
